CREATE TABLE IF NOT EXISTS vyaparis (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vyapari_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NULL,
    email_id VARCHAR(255) NULL,
    primary_number VARCHAR(20) NULL,
    secondary_number VARCHAR(20) NULL,
    gst_number VARCHAR(50) NULL,
    city VARCHAR(100) NULL,
    state VARCHAR(100) NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_vyaparis_name (vyapari_name),
    INDEX idx_vyaparis_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vyapari_id BIGINT UNSIGNED NULL,
    product_name VARCHAR(255) NOT NULL,
    purity DECIMAL(10,3) DEFAULT 0,
    rate DECIMAL(12,3) DEFAULT 0,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_products_vyapari (vyapari_id),
    INDEX idx_products_deleted (deleted_at),
    CONSTRAINT fk_products_vyapari FOREIGN KEY (vyapari_id) REFERENCES vyaparis(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vyapari_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NULL,
    transaction_type VARCHAR(50) NOT NULL,
    liya_diya ENUM('liya','diya') NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    gross_weight DECIMAL(14,3) DEFAULT 0,
    net_weight DECIMAL(14,3) DEFAULT 0,
    melting DECIMAL(8,3) DEFAULT 0,
    rate DECIMAL(10,3) DEFAULT 0,
    cash_charge_amount DECIMAL(14,2) DEFAULT 0,
    bill_charge_amount DECIMAL(14,2) DEFAULT 0,
    ten_gram_bill_995_rate DECIMAL(14,2) DEFAULT 0,
    ten_gram_cash_995_rate DECIMAL(14,2) DEFAULT 0,
    purity_999 DECIMAL(14,3) DEFAULT 0,
    purity_995 DECIMAL(14,3) DEFAULT 0,
    gst_bhav DECIMAL(14,2) DEFAULT 0,
    cash_bhav DECIMAL(14,2) DEFAULT 0,
    cash_amount DECIMAL(14,2) DEFAULT 0,
    rtgs_amount DECIMAL(14,2) DEFAULT 0,
    balance_cat_995 DECIMAL(14,3) DEFAULT 0,
    transaction_date DATE NOT NULL,
    notes TEXT NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_transactions_vyapari_date (vyapari_id, transaction_date),
    INDEX idx_transactions_type (transaction_type),
    INDEX idx_transactions_liya_diya (liya_diya),
    CONSTRAINT fk_transactions_vyapari FOREIGN KEY (vyapari_id) REFERENCES vyaparis(id) ON DELETE CASCADE,
    CONSTRAINT fk_transactions_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
